# Use Node.js as a base image
FROM node:16-slim

WORKDIR /app

RUN npm install -g firebase-tools

COPY firebase_creds.json ./

EXPOSE 9000 9099 8085

# Default command to run the Firebase Emulator
CMD ["firebase", "emulators:start", "--only", "auth,database,firestore"]
